{% set name = "sopsy" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sopsy-{{ version }}.tar.gz
  sha256: 2159a82f6fee10b7e29b688e4a0bdc1a50e96e8da2357ff46f97554aff0990f1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pyyaml >=6.0.1
    - go-sops

test:
  imports:
    - sopsy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: SOPS Python wrapper library
  license: MIT
  license_file: LICENSE
  home: https://github.com/nikaro/sopsy
  dev_url: https://github.com/nikaro/sopsy
  doc_url: https://sopsy.nikaro.net/

extra:
  recipe-maintainers:
    - FelixMoellerQC
    - pavelzw
